name: Reusable Trivy Scanner

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true

# 1. Permissions Lockdown
permissions:
  contents: read
  security-events: write  # Required to upload results to the Security tab

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # Scans the specific image version we just built
          image-ref: "${{ secrets.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}"
          format: 'table'
          exit-code: '1' # Fails the pipeline if CRITICAL/HIGH found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        # 4. Added step to upload the SARIF file
        # Pinned SHA for upload-sarif (v3.24.6)
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'


