name: Reusable Trivy Scanner

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true

# 1. Permissions Lockdown
permissions:
  contents: read
  security-events: write  # Required to upload results to the Security tab

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # DEBUG STEP: Let's see if the variables are correct
      - name: Debug Image Name
        run: |
          echo "Scanning image: ${{ secrets.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          image-ref: "docker.io/${{ secrets.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'  # Change to 0 temporarily to force the file creation
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        if: always()
        uses: github/codeql-action/upload-sarif@v3.24.6
        with:
          sarif_file: 'trivy-results.sarif'


